# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed6bbecc1df6c438af46409f5749a82c9c2c011c5f3f3e319325dc24cffa4dd554aec9954aecb4d644573b4a07953bfe6ce7d2185e4d7af972a4bbc6c3ad5597

test:
  secret_key_base: ab3d9e28df46d62695359360c14f923008dae026eccc75869746b7623fdf6571bcd5791ee5de6ea12218c331719aba70ba59f16ad795d876384b24187692b30f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
